name: core
description: Core business logic and domain models for Climbing Logbook
version: 1.0.0

environment:
  sdk: ^3.8.1

dependencies:
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  collection: ^1.18.0

dev_dependencies:
  test: ^1.25.0
  build_runner: ^2.4.13
  freezed: ^2.5.7
  json_serializable: ^6.8.0